import { collection, addDoc, serverTimestamp } from "firebase/firestore";
import { db } from "./firebase";

const dataBalita = [
  {
    nama: "Alya Putri",
    tanggalLahir: "2022-01-14",
    umur: "28",
    jk: "Perempuan",
    berat: "12.1",
    tinggi: "87",
    imunisasi: "Lengkap",
    asi: "Ya",
    penyakit: "-",
    gizi: "Baik",
    orangTua: "Rudi Hartono",
    hp: "081234560101",
    alamat: "Jl. Melati 1",
    provinsi: "Jawa Tengah",
    kota: "Kota Semarang",
    kecamatan: "Tembalang",
    wilayah: "Tembalang, Kota Semarang",
    kader: "Bu Rina",
    catatan: "-",
    risiko: "Rendah"
  },
  {
    nama: "Raka Pratama",
    tanggalLahir: "2023-02-11",
    umur: "15",
    jk: "Laki-laki",
    berat: "9.1",
    tinggi: "76",
    imunisasi: "Belum Lengkap",
    asi: "Ya",
    penyakit: "Batuk",
    gizi: "Kurang",
    orangTua: "Joko Widodo",
    hp: "081234560102",
    alamat: "Jl. Anggrek 2",
    provinsi: "Jawa Tengah",
    kota: "Kota Semarang",
    kecamatan: "Pedurungan",
    wilayah: "Pedurungan, Kota Semarang",
    kader: "Bu Maya",
    catatan: "Perlu pemantauan",
    risiko: "Tinggi"
  },
  {
    nama: "Nabila Sari",
    tanggalLahir: "2021-11-02",
    umur: "30",
    jk: "Perempuan",
    berat: "13.4",
    tinggi: "91",
    imunisasi: "Lengkap",
    asi: "Ya",
    penyakit: "-",
    gizi: "Baik",
    orangTua: "Agus Setiawan",
    hp: "081234560103",
    alamat: "Jl. Dahlia 4",
    provinsi: "DKI Jakarta",
    kota: "Jakarta Timur",
    kecamatan: "Duren Sawit",
    wilayah: "Duren Sawit, Jakarta Timur",
    kader: "Bu Lina",
    catatan: "-",
    risiko: "Rendah"
  },
  {
    nama: "Farel Nugraha",
    tanggalLahir: "2022-07-18",
    umur: "22",
    jk: "Laki-laki",
    berat: "10.0",
    tinggi: "80",
    imunisasi: "Belum Lengkap",
    asi: "Tidak",
    penyakit: "-",
    gizi: "Kurang",
    orangTua: "Slamet Riyadi",
    hp: "081234560104",
    alamat: "Jl. Kenanga",
    provinsi: "Jawa Timur",
    kota: "Kota Surabaya",
    kecamatan: "Wonokromo",
    wilayah: "Wonokromo, Kota Surabaya",
    kader: "Bu Sinta",
    catatan: "Cek gizi",
    risiko: "Sedang"
  },
  {
    nama: "Tiara Maharani",
    tanggalLahir: "2021-08-20",
    umur: "33",
    jk: "Perempuan",
    berat: "14.1",
    tinggi: "94",
    imunisasi: "Lengkap",
    asi: "Ya",
    penyakit: "-",
    gizi: "Baik",
    orangTua: "Bambang",
    hp: "081234560105",
    alamat: "Jl. Sakura",
    provinsi: "Jawa Barat",
    kota: "Kota Bandung",
    kecamatan: "Coblong",
    wilayah: "Coblong, Kota Bandung",
    kader: "Bu Dewi",
    catatan: "-",
    risiko: "Rendah"
  },
  {
    nama: "Daffa Ramadhan",
    tanggalLahir: "2023-03-12",
    umur: "14",
    jk: "Laki-laki",
    berat: "8.8",
    tinggi: "73",
    imunisasi: "Belum Lengkap",
    asi: "Tidak",
    penyakit: "Diare",
    gizi: "Kurang",
    orangTua: "Yanto",
    hp: "081234560106",
    alamat: "Jl. Tulip",
    provinsi: "Sumatera Utara",
    kota: "Kota Medan",
    kecamatan: "Medan Johor",
    wilayah: "Medan Johor, Kota Medan",
    kader: "Bu Nia",
    catatan: "Prioritas",
    risiko: "Tinggi"
  },
  {
    nama: "Nayla Zahra",
    tanggalLahir: "2022-04-10",
    umur: "26",
    jk: "Perempuan",
    berat: "11.8",
    tinggi: "85",
    imunisasi: "Lengkap",
    asi: "Ya",
    penyakit: "-",
    gizi: "Baik",
    orangTua: "Rahmat",
    hp: "081234560107",
    alamat: "Jl. Mawar",
    provinsi: "Banten",
    kota: "Kota Tangerang",
    kecamatan: "Ciledug",
    wilayah: "Ciledug, Kota Tangerang",
    kader: "Bu Wati",
    catatan: "-",
    risiko: "Rendah"
  },
  {
    nama: "Rizky Saputra",
    tanggalLahir: "2023-01-01",
    umur: "17",
    jk: "Laki-laki",
    berat: "9.5",
    tinggi: "77",
    imunisasi: "Belum Lengkap",
    asi: "Ya",
    penyakit: "-",
    gizi: "Kurang",
    orangTua: "Dedi",
    hp: "081234560108",
    alamat: "Jl. Flamboyan",
    provinsi: "DI Yogyakarta",
    kota: "Kota Yogyakarta",
    kecamatan: "Umbulharjo",
    wilayah: "Umbulharjo, Kota Yogyakarta",
    kader: "Bu Nanik",
    catatan: "-",
    risiko: "Sedang"
  },
  {
    nama: "Salsa Putri",
    tanggalLahir: "2022-09-08",
    umur: "20",
    jk: "Perempuan",
    berat: "10.9",
    tinggi: "82",
    imunisasi: "Lengkap",
    asi: "Ya",
    penyakit: "-",
    gizi: "Baik",
    orangTua: "Andri",
    hp: "081234560109",
    alamat: "Jl. Cemara",
    provinsi: "Bali",
    kota: "Kota Denpasar",
    kecamatan: "Denpasar Barat",
    wilayah: "Denpasar Barat, Kota Denpasar",
    kader: "Bu Komang",
    catatan: "-",
    risiko: "Rendah"
  },
  {
    nama: "Bagas Aditya",
    tanggalLahir: "2023-04-19",
    umur: "13",
    jk: "Laki-laki",
    berat: "8.9",
    tinggi: "74",
    imunisasi: "Belum Lengkap",
    asi: "Tidak",
    penyakit: "-",
    gizi: "Kurang",
    orangTua: "Wahyu",
    hp: "081234560110",
    alamat: "Jl. Merpati",
    provinsi: "Sulawesi Selatan",
    kota: "Kota Makassar",
    kecamatan: "Panakkukang",
    wilayah: "Panakkukang, Kota Makassar",
    kader: "Bu Indah",
    catatan: "Kontrol bulanan",
    risiko: "Tinggi"
  }
];

async function seedBalita() {
  try {
    for (let i = 0; i < dataBalita.length; i++) {
      await addDoc(collection(db, "balita"), {
        ...dataBalita[i],
        createdAt: serverTimestamp()
      });
    }

    console.log("25 data berhasil diimport");
  } catch (error) {
    console.log(error);
  }
}

seedBalita();